[package]
name = "diffy-queue"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
plotters = "0.3.0"
meval = "0.2"
num = "0.4.0"
prettytable-rs = "0.8.0"
ctrlc = "3.1.9"